name: 'Setup Node + NPM + Install Dependencies'
description: 'Setup Node + NPM + Install Dependencies'

inputs:
  node-version:
    description: 'The version of Node.js to use'
    required: true
    default: '20.x'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: 📦 Install Project Dependencies
      run: npm ci
      shell: bash
