name: Run Linting

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + NPM + install deps
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        name: Install Dependencies

      - name: 🏃‍♂️ Run ESLint
        run: npm run lint

      - name: 🏃‍♂️ Report ESLint Results
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'
        #  fail_on_error: true  # Fail the action on ESLint errors

      - name: 🏃‍♂️ Run ESLint on Push
        if: github.event_name != 'pull_request'
        run: npm run lint
