name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    strategy:
      matrix:
        node-version: [20.x]

    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Retrieve Git history, needed to verify commits

      - name: 📦 Setup Node + NPM + install deps
        uses: ./.github/actions/setup-node-npm-install
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🏃🏾‍♂️ Run unit tests
        run: npm run test -- --coverage

      #   - name: ✅ Upload coverage reports to Codecov
      #     uses: codecov/codecov-action@v4
      #     env:
      #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-results
          path: test-results/
          retention-days: 7
